# Generated by Django 3.2 on 2022-03-31 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0009_publicnumbers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='活动名称')),
                ('start_time', models.DateTimeField(verbose_name='活动开始时间')),
                ('end_time', models.DateTimeField(verbose_name='活动结束时间')),
                ('protect_switch', models.SmallIntegerField(choices=[(1, '开'), (2, '关')], default=1, verbose_name='拉新保护')),
                ('mtb_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.userinfo', verbose_name='创建人')),
            ],
        ),
        migrations.CreateModel(
            name='TakePartIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_id', models.CharField(max_length=64, verbose_name='粉丝OpenID')),
                ('nick_name', models.CharField(blank=True, max_length=64, null=True, verbose_name='粉丝昵称')),
                ('avatar', models.FileField(blank=True, null=True, upload_to='', verbose_name='粉丝头像')),
                ('origin', models.IntegerField(choices=[(0, '其他粉丝'), (1, '推广码'), (2, '其他')], default=2, verbose_name='粉丝来源')),
                ('looking', models.IntegerField(choices=[(0, '关注中'), (1, '已取关')], default=0, verbose_name='关注状态')),
                ('part_in', models.IntegerField(choices=[(0, '参与'), (1, '不参与')], default=0, verbose_name='参与活动')),
                ('poster', models.CharField(max_length=128, null=True, verbose_name='专属拉新海报')),
                ('black', models.IntegerField(choices=[(0, '未加入黑名单'), (1, '加入黑名单')], default=0, verbose_name='黑名单开关')),
                ('level', models.IntegerField(default=1, verbose_name='裂变层级')),
                ('origin_open_id', models.CharField(max_length=64, null=True, verbose_name='来源ID')),
                ('number', models.IntegerField(default=0, verbose_name='邀请人数')),
                ('task_progress', models.IntegerField(choices=[(0, '参与'), (1, '完成任务一'), (2, '完成任务二'), (3, '完成任务三')], default=0, verbose_name='任务完成度')),
                ('ctime', models.DateTimeField(auto_now_add=True, verbose_name='参与时间')),
                ('task_end_time', models.DateTimeField(null=True, verbose_name='完成时间')),
                ('subscribe_time', models.DateTimeField(verbose_name='关注时间')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.activity', verbose_name='活动')),
                ('public_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.publicnumbers', verbose_name='公众号')),
            ],
        ),
        migrations.CreateModel(
            name='PublicJoinActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publics', to='task.activity', verbose_name='活动')),
                ('public', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.publicnumbers', verbose_name='公众号')),
            ],
        ),
        migrations.CreateModel(
            name='PosterSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_img', models.CharField(max_length=128, verbose_name='背景图片')),
                ('key_word', models.CharField(max_length=10, verbose_name='海报生成关键字')),
                ('rule', models.CharField(max_length=256, verbose_name='活动规则描述')),
                ('activity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='poster', to='task.activity', verbose_name='活动')),
            ],
        ),
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(choices=[(1, '一阶任务'), (2, '二阶任务'), (3, '三阶任务')], default=1, verbose_name='任务等级')),
                ('number', models.IntegerField(default=0, verbose_name='任务数量')),
                ('good', models.CharField(max_length=255, verbose_name='奖品')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='task.activity', verbose_name='参与活动')),
            ],
        ),
    ]
