# Generated by Django 3.2 on 2022-03-31 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='takepartin',
            name='task_end_time',
        ),
        migrations.AlterField(
            model_name='takepartin',
            name='poster',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='专属拉新海报'),
        ),
    ]
