# Generated by Django 3.2 on 2022-04-01 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_auto_20220401_0734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='protect_switch',
            field=models.BooleanField(verbose_name='拉新保护'),
        ),
    ]
