# Generated by Django 3.2 on 2022-04-01 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_rename_goods_award_good'),
    ]

    operations = [
        migrations.RenameField(
            model_name='award',
            old_name='good',
            new_name='goods',
        ),
    ]
