# Generated by Django 3.2 on 2022-04-01 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0007_alter_award_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postersetting',
            old_name='rule',
            new_name='rules',
        ),
    ]
