# Generated by Django 3.2 on 2022-04-01 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0008_rename_rule_postersetting_rules'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postersetting',
            old_name='key_word',
            new_name='key',
        ),
    ]
