# Generated by Django 3.2 on 2022-04-01 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0009_rename_key_word_postersetting_key'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postersetting',
            old_name='background_img',
            new_name='img',
        ),
    ]
