# Generated by Django 3.2 on 2022-04-01 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0010_rename_background_img_postersetting_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='award',
            old_name='number',
            new_name='count',
        ),
    ]
