# Generated by Django 3.2 on 2022-04-01 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0011_rename_number_award_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='takepartin',
            name='origin_open_id',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='来源ID'),
        ),
        migrations.AlterField(
            model_name='takepartin',
            name='subscribe_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='关注时间'),
        ),
    ]
