# Generated by Django 3.2 on 2022-04-02 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_publicnumbers'),
        ('task', '0012_auto_20220401_1944'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='渠道名称')),
                ('qr', models.CharField(max_length=128, verbose_name='二维码')),
                ('mtb_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.userinfo', verbose_name='创建人')),
                ('public_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.publicnumbers', verbose_name='公众号')),
            ],
        ),
    ]
