# Generated by Django 3.2 on 2022-04-02 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0013_promo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promo',
            name='qr',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='二维码'),
        ),
    ]
