# Generated by Django 3.2 on 2022-04-02 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0014_alter_promo_qr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promo',
            old_name='public_number',
            new_name='public',
        ),
    ]
