# Generated by Django 3.2 on 2022-04-02 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0015_rename_public_number_promo_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='takepartin',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='task.activity', verbose_name='活动'),
        ),
    ]
