# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-01-15 01:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200115_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='avatar',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='token',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='用户Token'),
        ),
    ]
