# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-12-27 07:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_auto_20181226_1101'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_num', models.IntegerField(verbose_name='节次')),
                ('date', models.DateField(auto_now_add=True, verbose_name='上课日期')),
                ('class_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.ClassList', verbose_name='班级')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.UserInfo', verbose_name='讲师')),
            ],
        ),
        migrations.RemoveField(
            model_name='interviewrecord',
            name='student',
        ),
        migrations.RemoveField(
            model_name='interviewrecord',
            name='user',
        ),
        migrations.DeleteModel(
            name='InterviewRecord',
        ),
    ]
