# Generated by Django 2.2 on 2022-02-21 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': '01-课程分类表', 'verbose_name_plural': '01-课程分类表'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': '02-课程表', 'verbose_name_plural': '02-课程表'},
        ),
        migrations.AlterModelOptions(
            name='coursedetail',
            options={'verbose_name': '03-课程详细表', 'verbose_name_plural': '03-课程详细表'},
        ),
    ]
