# Generated by Django 2.2 on 2022-02-26 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0003_auto_20220221_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='username',
            field=models.CharField(max_length=32, unique=True, verbose_name='用户姓名'),
        ),
    ]
