# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-01-17 02:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200117_1036'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auction',
            options={'verbose_name_plural': '拍卖表'},
        ),
        migrations.AlterModelOptions(
            name='depart',
            options={'verbose_name_plural': '部门表'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name_plural': '标签表'},
        ),
        migrations.AlterField(
            model_name='auction',
            name='dp',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.Depart', verbose_name='部门'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='status',
            field=models.IntegerField(choices=[(1, '在职'), (2, '离职')], default=1, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='tags',
            field=models.ManyToManyField(default=1, to='api.Tag', verbose_name='标签'),
        ),
    ]
