# Generated by Django 3.2 on 2022-03-26 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_wxcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wxcode',
            name='code_type',
            field=models.IntegerField(choices=[(1, 'component_verify_ticket'), (2, 'component_access_token'), (3, 'pre_auth_code')], verbose_name='类型'),
        ),
    ]
