# Generated by Django 3.2 on 2022-03-26 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_wxcode_code_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wxcode',
            name='value',
            field=models.CharField(max_length=255, verbose_name='值'),
        ),
    ]
