# Generated by Django 3.2 on 2022-03-28 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_publicnumbers_authorizer_access_token'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PublicNumbers',
        ),
    ]
