# Generated by Django 3.2 on 2022-03-28 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_delete_publicnumbers'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicNumbers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authorizer_app_id', models.CharField(max_length=64, verbose_name='授权ID')),
                ('authorizer_access_token', models.CharField(max_length=255, verbose_name='授权token')),
                ('authorizer_refresh_token', models.CharField(max_length=64, verbose_name='授权更新token')),
                ('authorizer_period', models.PositiveIntegerField(verbose_name='过期时间')),
                ('nick_name', models.CharField(max_length=32, verbose_name='公众号名称')),
                ('user_name', models.CharField(max_length=64, verbose_name='公众号原始ID')),
                ('avatar', models.CharField(max_length=128, verbose_name='公众号头像')),
                ('service_type_info', models.IntegerField(choices=[(0, '订阅号'), (1, '由历史老帐号升级后的订阅号'), (2, '服务号')], verbose_name='公众号类型')),
                ('verify_type_info', models.IntegerField(choices=[(-1, '未认证'), (0, '微信认证'), (1, '新浪微博认证'), (2, '腾讯微博认证'), (3, '已资质认证通过但还未通过名称认证'), (4, '已资质认证通过、还未通过名称认证，但通过了新浪微博认证'), (5, '已资质认证通过、还未通过名称认证，但通过了腾讯微博认证')], verbose_name='认证类型')),
                ('mtb_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.userinfo', verbose_name='媒体宝用户')),
            ],
        ),
    ]
