# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-01-18 03:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='商品名称')),
                ('price', models.PositiveIntegerField(verbose_name='价格')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField(choices=[(1, '待支付'), (2, '已支付')], verbose_name='状态')),
                ('uid', models.CharField(max_length=64, verbose_name='订单号')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Goods', verbose_name='商品')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=32, verbose_name='手机号')),
                ('token', models.CharField(max_length=32, verbose_name='Token')),
                ('openid', models.CharField(max_length=32, verbose_name='微信唯一标识')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.UserInfo', verbose_name='用户'),
        ),
    ]
