# Generated by Django 2.2 on 2021-11-10 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usser',
            new_name='User',
        ),
    ]
