# Generated by Django 3.2.4 on 2021-06-27 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='标题')),
                ('detail', models.TextField(blank=True, null=True, verbose_name='描述')),
            ],
        ),
        migrations.CreateModel(
            name='AuditTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField(choices=[(1, '未审批'), (2, '待审批'), (3, '通过'), (4, '未通过')], verbose_name='状态')),
                ('user', models.CharField(max_length=32, verbose_name='审批者')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='app01.audittask', verbose_name='上一级（下一个）')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.task', verbose_name='任务/工单')),
            ],
        ),
    ]
