# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-01-13 00:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20200113_0033'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsFavorRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ViewerRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='news',
            name='favor',
        ),
        migrations.RemoveField(
            model_name='news',
            name='viewer',
        ),
        migrations.AddField(
            model_name='viewerrecord',
            name='news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.News', verbose_name='动态'),
        ),
        migrations.AddField(
            model_name='viewerrecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.UserInfo', verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='newsfavorrecord',
            name='news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.News', verbose_name='动态'),
        ),
        migrations.AddField(
            model_name='newsfavorrecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.UserInfo', verbose_name='点赞用户'),
        ),
    ]
