# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-01-13 03:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20200113_0253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentfavorrecord',
            name='news',
        ),
        migrations.AddField(
            model_name='commentfavorrecord',
            name='comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.CommentRecord', verbose_name='动态'),
            preserve_default=False,
        ),
    ]
