# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-01-17 18:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_auto_20200117_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='openid',
            field=models.CharField(default=1, max_length=32, verbose_name='微信用户唯一标识'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo',
            name='session_key',
            field=models.CharField(default=1, max_length=32, verbose_name='微信会话秘钥'),
            preserve_default=False,
        ),
    ]
