# Generated by Django 2.2 on 2020-01-14 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20200113_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='save_id',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='编辑历史ID'),
        ),
        migrations.AlterField(
            model_name='articlecollection',
            name='name',
            field=models.CharField(max_length=200, verbose_name='文集标题'),
        ),
    ]
