# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-04 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_auto_20191204_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagram',
            name='status',
            field=models.CharField(choices=[('gray', '待执行'), ('green', '成功'), ('red', '失败')], default='gray', max_length=32, verbose_name='状态'),
        ),
    ]
