# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-12-06 07:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_remove_diagram_is_diagram'),
    ]

    operations = [
        migrations.AddField(
            model_name='deploytask',
            name='title',
            field=models.CharField(default='ff', max_length=64, verbose_name='名称'),
            preserve_default=False,
        ),
    ]
