# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-12-06 07:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_deploytask_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deploytask',
            name='title',
        ),
        migrations.AddField(
            model_name='deploytask',
            name='summary',
            field=models.CharField(default='x', max_length=64, verbose_name='描述'),
            preserve_default=False,
        ),
    ]
