# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-12-09 05:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_remove_hookscript_env'),
    ]

    operations = [
        migrations.AddField(
            model_name='hookscript',
            name='hook_type',
            field=models.IntegerField(choices=[(2, '下载前'), (4, '下载后'), (7, '发布前'), (9, '发布后')], default=1, verbose_name='钩子类型'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hookscript',
            name='title',
            field=models.CharField(default=1, max_length=32, verbose_name='标题'),
            preserve_default=False,
        ),
    ]
