# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-05-06 06:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_auto_20200506_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='api_data',
            field=models.CharField(default={}, max_length=255, verbose_name='请求data'),
        ),
        migrations.AlterField(
            model_name='api',
            name='api_desc',
            field=models.CharField(default='', max_length=255, verbose_name='用例描述'),
        ),
        migrations.AlterField(
            model_name='api',
            name='api_expect',
            field=models.CharField(default={}, max_length=4196, verbose_name='预期结果'),
        ),
        migrations.AlterField(
            model_name='api',
            name='api_params',
            field=models.CharField(default={}, max_length=255, verbose_name='请求参数'),
        ),
        migrations.AlterField(
            model_name='api',
            name='api_report',
            field=models.TextField(default='', verbose_name='报告'),
        ),
        migrations.AlterField(
            model_name='api',
            name='api_url',
            field=models.CharField(default='', max_length=255, verbose_name='请求URL'),
        ),
    ]
