# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-12-26 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_paymentrecord_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='memo',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='备注'),
        ),
    ]
