# Generated by Django 2.2 on 2020-02-16 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_record_goods_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='alipay_account',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='支付宝账号'),
        ),
        migrations.AlterField(
            model_name='record',
            name='goods_type',
            field=models.IntegerField(choices=[(0, '其他'), (1, '文章')], default=0, verbose_name='物品类型'),
        ),
        migrations.AlterField(
            model_name='record',
            name='status',
            field=models.IntegerField(choices=[(0, '未支付'), (1, '已支付')], default=0, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='record',
            name='types',
            field=models.IntegerField(choices=[(0, '赞赏'), (1, '购买'), (2, '提现'), (3, '充值'), (4, '其他')], default=4, verbose_name='类型'),
        ),
    ]
