# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-01-12 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20200112_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentrecord',
            name='favor_count',
            field=models.PositiveIntegerField(default=0, verbose_name='赞数'),
        ),
    ]
