# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-02-11 23:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_auctiontask'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctiontask',
            name='auction_end_status',
        ),
        migrations.RemoveField(
            model_name='auctiontask',
            name='auction_status',
        ),
        migrations.RemoveField(
            model_name='auctiontask',
            name='preview_status',
        ),
    ]
