# Generated by Django 2.0.1 on 2018-06-09 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20180508_1542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='comment_num',
        ),
        migrations.RemoveField(
            model_name='book',
            name='read_num',
        ),
    ]
