# Generated by Django 2.2 on 2022-02-26 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0004_auto_20220226_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='username',
            field=models.CharField(max_length=32, verbose_name='用户姓名'),
        ),
    ]
