# Generated by Django 2.2 on 2022-02-26 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0005_auto_20220226_0848'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='role',
            field=models.SmallIntegerField(blank=True, max_length=32, null=True, verbose_name='角色'),
        ),
        migrations.AlterField(
            model_name='account',
            name='username',
            field=models.CharField(max_length=32, unique=True, verbose_name='用户姓名'),
        ),
    ]
