# Generated by Django 3.2 on 2021-12-26 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app02', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='classes',
            field=models.IntegerField(choices=[(11, '全栈1期'), (21, '全栈3期')], default=11, verbose_name='班级'),
        ),
    ]
