# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-05-06 01:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='It',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('it_name', models.CharField(default='', max_length=32, verbose_name='项目名称')),
                ('it_desc', models.TextField(default='', max_length=255, verbose_name='项目描述')),
                ('it_start_tile', models.DateField(verbose_name='项目开始时间')),
                ('it_end_tile', models.DateField(verbose_name='项目结束时间')),
            ],
        ),
    ]
