# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-01-19 03:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20200117_1055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='dp',
        ),
        migrations.RemoveField(
            model_name='auction',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Auction',
        ),
        migrations.DeleteModel(
            name='Depart',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
