# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-01-19 08:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auction_auctionitem_auctionitemdetail_auctionitemimage_bidrecord_browserecord_depositrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='balance',
            field=models.PositiveIntegerField(default=1000, verbose_name='余额'),
        ),
        migrations.AlterField(
            model_name='auctionitem',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, '待拍卖'), (2, '预展中'), (3, '拍卖中'), (4, '成交'), (5, '流拍')], default=1, verbose_name='状态'),
        ),
    ]
