# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-12-26 01:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ready', '未开拍'), ('preview', '预展中'), ('auction', '拍卖中'), ('stop', '已结束')], default='ready', max_length=16, verbose_name='状态')),
                ('title', models.CharField(max_length=32, verbose_name='标题')),
                ('img', models.CharField(max_length=64, verbose_name='拍卖图')),
                ('video', models.CharField(max_length=128, verbose_name='预览视频')),
                ('preview_start_time', models.DateTimeField(verbose_name='预展开始时间')),
                ('preview_end_time', models.DateTimeField(verbose_name='预展结束时间')),
                ('auction_start_time', models.DateTimeField(verbose_name='拍卖开始时间')),
                ('auction_end_time', models.DateTimeField(verbose_name='拍卖结束时间')),
                ('total_price', models.PositiveIntegerField(blank=True, null=True, verbose_name='成交额')),
                ('goods_count', models.PositiveIntegerField(default=0, verbose_name='拍品数量')),
                ('bid_count', models.PositiveIntegerField(default=0, verbose_name='出价次数')),
                ('look_count', models.PositiveIntegerField(default=0, verbose_name='围观次数')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
        ),
        migrations.CreateModel(
            name='AuctionItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=12, verbose_name='图录号')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, '未开拍'), (2, '拍卖中'), (3, '成交'), (4, '流拍')], default=1, verbose_name='状态')),
                ('title', models.CharField(max_length=32, verbose_name='拍品名称')),
                ('img', models.CharField(max_length=64, verbose_name='拍品图')),
                ('deal_price', models.PositiveIntegerField(blank=True, null=True, verbose_name='成交价')),
                ('reserve_price', models.PositiveIntegerField(verbose_name='参考底价')),
                ('highest_price', models.PositiveIntegerField(verbose_name='参考高价')),
                ('video', models.CharField(max_length=128, verbose_name='预览视频')),
                ('deposit', models.PositiveIntegerField(verbose_name='保证金')),
                ('unit', models.PositiveIntegerField(default=100, verbose_name='加价幅度')),
                ('bid_count', models.PositiveIntegerField(default=0, verbose_name='出价次数')),
                ('look_count', models.PositiveIntegerField(default=0, verbose_name='围观次数')),
            ],
        ),
        migrations.CreateModel(
            name='AuctionItemDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=64, verbose_name='详细图')),
                ('carousel', models.BooleanField(default=False, verbose_name='是否在轮播中显示')),
                ('order', models.FloatField(default=1, verbose_name='排序')),
            ],
        ),
        migrations.CreateModel(
            name='BidRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, '竞价'), (2, '成交')], default=1, verbose_name='状态')),
                ('price', models.PositiveIntegerField(verbose_name='出价')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.AuctionItem', verbose_name='拍品')),
            ],
        ),
        migrations.CreateModel(
            name='BrowseRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.AuctionItem', verbose_name='拍品')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.CharField(max_length=64, verbose_name='头像')),
                ('telephone', models.CharField(max_length=11, verbose_name='手机号')),
            ],
        ),
        migrations.AddField(
            model_name='browserecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.UserInfo', verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='bidrecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.UserInfo', verbose_name='出价人'),
        ),
    ]
