# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-01-16 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_auto_20200116_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='cover',
            field=models.FileField(max_length=64, upload_to='', verbose_name='封面'),
        ),
    ]
