# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-02-12 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_auto_20200212_0738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='deposit_price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='real_price',
        ),
        migrations.AddField(
            model_name='depositrecord',
            name='balance',
            field=models.PositiveIntegerField(default=0, verbose_name='余额'),
        ),
        migrations.AlterField(
            model_name='depositrefundrecord',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, '待退款'), (2, '退款成功')], verbose_name='状态'),
        ),
    ]
