# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-02-14 06:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0056_coupon_task_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='task_id',
        ),
        migrations.AddField(
            model_name='coupon',
            name='apply_end_task_id',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='celery任务ID'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='apply_start_task_id',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='celery任务ID'),
        ),
    ]
