# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-01-11 01:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20200111_0107'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsimage',
            name='key',
            field=models.CharField(default='x', max_length=128, verbose_name='腾讯对象存储key'),
            preserve_default=False,
        ),
    ]
