# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-01-11 02:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_newsimage_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='nickname',
            field=models.CharField(default='wupeiqi', max_length=64, verbose_name='昵称'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='newsimage',
            name='key',
            field=models.CharField(help_text='用于以后在腾讯对象存储中删除', max_length=128, verbose_name='腾讯对象存储中的文件路径'),
        ),
    ]
