# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-06 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_time',
            field=models.IntegerField(choices=[(1, '8:00'), (2, '9:00'), (3, '10:00'), (4, '11:00'), (5, '12:00'), (6, '13:00'), (7, '14:00'), (8, '15:00'), (9, '16:00'), (10, '17:00'), (11, '18:00'), (12, '19:00'), (13, '20:00')], verbose_name='预定时间段'),
        ),
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together=set([('booking_date', 'booking_time', 'room')]),
        ),
    ]
