# Generated by Django 2.2 on 2019-06-24 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_department_userinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='nickname',
            field=models.CharField(default=111, max_length=32, verbose_name='姓名'),
            preserve_default=False,
        ),
    ]
