# Generated by Django 2.2 on 2019-06-28 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_auto_20190628_0924'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courserecord',
            old_name='course_meno',
            new_name='course_memo',
        ),
        migrations.AlterField(
            model_name='studyrecord',
            name='homework_score',
            field=models.PositiveIntegerField(default=0, verbose_name='作业成绩'),
        ),
    ]
