# Generated by Django 3.2 on 2022-04-06 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('age', models.IntegerField()),
                ('birth', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('createDate', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
