# Generated by Django 2.0.1 on 2021-10-20 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_emp'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='comment_sum',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='book',
            name='read_sum',
            field=models.IntegerField(default=0),
        ),
    ]
