# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-12-26 10:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_auto_20181226_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='score',
            field=models.IntegerField(default=100, verbose_name='积分'),
        ),
    ]
