# Generated by Django 3.2 on 2021-10-08 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20211008_1341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='classmate',
        ),
        migrations.RemoveField(
            model_name='student',
            name='description',
        ),
    ]
