# Generated by Django 3.2 on 2021-10-09 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_alter_student_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='description',
        ),
        migrations.AlterField(
            model_name='student',
            name='age',
            field=models.SmallIntegerField(default=18, verbose_name='年龄'),
        ),
    ]
