# Generated by Django 3.2 on 2021-10-09 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_student_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='chinese_score',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='student',
            name='math_score',
            field=models.IntegerField(default=100),
        ),
    ]
