# Generated by Django 3.2 on 2021-12-26 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app02', '0004_project_classes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='classes',
        ),
    ]
