# Generated by Django 3.2.5 on 2021-07-04 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_userinfo_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='xx',
            field=models.IntegerField(default=1, verbose_name='xx'),
            preserve_default=False,
        ),
    ]
