# Generated by Django 3.2.5 on 2021-07-04 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_userinfo_xx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='xx',
        ),
    ]
