# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-12-26 01:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20191226_0121'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionitem',
            name='auction',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.Auction', verbose_name='拍卖'),
            preserve_default=False,
        ),
    ]
