# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-01-08 06:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200108_0610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='token',
            field=models.CharField(max_length=64, verbose_name='用户Token'),
        ),
    ]
