# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-02-14 06:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0054_auto_20200212_2037'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField(choices=[(1, '未开始'), (2, '领取中'), (3, '已结束')], default=1, verbose_name='状态')),
                ('title', models.CharField(max_length=32, verbose_name='优惠券名称')),
                ('money', models.PositiveIntegerField(default=0, verbose_name='抵扣金额')),
                ('count', models.PositiveIntegerField(verbose_name='创建数量')),
                ('remain_count', models.PositiveIntegerField(verbose_name='剩余数量')),
                ('apply_start_date', models.DateTimeField(verbose_name='开始领取时间')),
                ('apply_end_date', models.DateTimeField(verbose_name='领取结束时间')),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Auction', verbose_name='专场')),
            ],
        ),
        migrations.CreateModel(
            name='UserCoupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField(choices=[(1, '未使用'), (2, '已使用'), (3, '已过期')], default=1, verbose_name='状态')),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Coupon', verbose_name='优惠券')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Order', verbose_name='订单')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.UserInfo', verbose_name='用户')),
            ],
        ),
        migrations.AlterField(
            model_name='depositrecord',
            name='balance',
            field=models.PositiveIntegerField(verbose_name='余额'),
        ),
    ]
