# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-02-14 06:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0055_auto_20200214_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='task_id',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='celery任务ID'),
        ),
    ]
