# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-02-14 07:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0059_auto_20200214_1435'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='remain_count',
        ),
        migrations.AddField(
            model_name='coupon',
            name='apply_count',
            field=models.PositiveIntegerField(default=0, verbose_name='已申请数量'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='count',
            field=models.PositiveIntegerField(default=100, verbose_name='创建数量'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='money',
            field=models.PositiveIntegerField(default=200, verbose_name='抵扣金额'),
        ),
    ]
