# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-02-14 07:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0060_auto_20200214_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='是否删除'),
        ),
    ]
