# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-02-17 03:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0063_order_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='city',
        ),
        migrations.AddField(
            model_name='depositdeduct',
            name='deduct_type',
            field=models.SmallIntegerField(choices=[(1, '逾期扣款'), (2, '支付抵扣')], default=1, verbose_name='扣款类型'),
        ),
        migrations.AddField(
            model_name='order',
            name='pay_type',
            field=models.SmallIntegerField(choices=[(1, '微信'), (2, '余额')], default=1, verbose_name='支付方式'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='real_price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='实际支付金额'),
        ),
        migrations.AlterField(
            model_name='address',
            name='detail',
            field=models.CharField(max_length=255, verbose_name='收货地址'),
        ),
    ]
