# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-02-17 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0064_auto_20200217_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pay_type',
            field=models.SmallIntegerField(blank=True, choices=[(1, '微信'), (2, '余额')], null=True, verbose_name='支付方式'),
        ),
    ]
