# Generated by Django 3.2 on 2022-03-29 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msg', '0002_message_media_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interaction',
            old_name='open_id',
            new_name='user_open_id',
        ),
        migrations.RemoveField(
            model_name='interaction',
            name='public',
        ),
        migrations.AddField(
            model_name='interaction',
            name='authorizer_app_id',
            field=models.CharField(default=1, max_length=64, verbose_name='公众号授权ID'),
            preserve_default=False,
        ),
    ]
