/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_nb_jnikiller_DynamicUtils */

#ifndef _Included_com_nb_jnikiller_DynamicUtils
#define _Included_com_nb_jnikiller_DynamicUtils
#ifdef __cplusplus
extern "C" {
#endif

jint plus(JNIEnv *env, jobject obj, jint v1, jint v2) {
    return v1 + v2;
}


static JNINativeMethod gMethods[] = {
        {"add", "(II)I", (void *) plus},
};


/*
* System.loadLibrary("包")时会自动调用
* 如果成功返回JNI版本, 失败返回-1
*/
JNIEXPORT jint JNICALL JNI_OnLoad(JavaVM *vm, void *reserved) {


    JNIEnv *env = NULL;

    // 在java虚拟机中获取 env
    if ((*vm)->GetEnv(vm, (void **) &env, JNI_VERSION_1_6) != JNI_OK) {
        return JNI_ERR;
    }



    // 找到Java中的类
    jclass clazz = (*env)->FindClass(env, "com/nb/day09/DynamicUtils");

    // 将类中的方法注册到JNI中
    int res = (*env)->RegisterNatives(env, clazz, gMethods, 1);
    if (res < 0) {
        return JNI_ERR;
    }

    return JNI_VERSION_1_6;
}

#ifdef __cplusplus
}
#endif
#endif
