# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-12-26 11:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_auto_20181226_1101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interviewrecord',
            name='create_date',
        ),
        migrations.RemoveField(
            model_name='scorerecord',
            name='create_date',
        ),
    ]
