# Generated by Django 2.0 on 2018-10-16 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SerDemo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='Author',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='chapter',
            new_name='category',
        ),
    ]
