# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-01-15 01:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200115_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='count',
            field=models.PositiveIntegerField(default=0, verbose_name='关注度'),
        ),
    ]
