# Generated by Django 2.2 on 2019-06-28 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_auto_20190627_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='courserecord',
            name='course_meno',
            field=models.TextField(blank=True, null=True, verbose_name='内容概要'),
        ),
        migrations.AddField(
            model_name='courserecord',
            name='course_title',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='本节课程名称'),
        ),
        migrations.AddField(
            model_name='courserecord',
            name='homework',
            field=models.TextField(blank=True, null=True, verbose_name='作业内容'),
        ),
        migrations.AddField(
            model_name='studyrecord',
            name='homework_score',
            field=models.IntegerField(default=0, verbose_name='作业成绩'),
        ),
        migrations.AddField(
            model_name='studyrecord',
            name='homework_url',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='作业'),
        ),
        migrations.AlterField(
            model_name='classlist',
            name='class_teacher',
            field=models.ForeignKey(limit_choices_to={'depart__title': '教务部'}, on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='web.UserInfo', verbose_name='班主任'),
        ),
        migrations.AlterField(
            model_name='classlist',
            name='tech_teachers',
            field=models.ManyToManyField(blank=True, limit_choices_to={'depart__title': '教学部'}, related_name='teach_classes', to='web.UserInfo', verbose_name='任课老师'),
        ),
    ]
