# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-12-26 01:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20191226_0119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionitem',
            name='video',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='预览视频'),
        ),
    ]
