# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-01-11 10:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20200111_0913'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewsImage',
            new_name='NewsDetail',
        ),
    ]
