# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-01-17 02:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_auto_20200117_0201'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionItemDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=16, verbose_name='项')),
                ('value', models.CharField(max_length=32, verbose_name='值')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.AuctionItem', verbose_name='拍品')),
            ],
        ),
        migrations.AddField(
            model_name='auctionitemimage',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.AuctionItem', verbose_name='拍品'),
            preserve_default=False,
        ),
    ]
