# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-01-20 21:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_auto_20200117_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='fans_count',
            field=models.PositiveIntegerField(default=0, verbose_name='粉丝个数'),
        ),
        migrations.AlterField(
            model_name='auctionitem',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, '待成交'), (1, '拍卖中'), (2, '成交'), (3, '流拍')], default=1, verbose_name='状态'),
        ),
    ]
