# Generated by Django 3.2 on 2021-10-11 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='classAddr',
        ),
        migrations.RemoveField(
            model_name='course',
            name='classTime',
        ),
        migrations.RemoveField(
            model_name='course',
            name='credit',
        ),
        migrations.RemoveField(
            model_name='course',
            name='teacher',
        ),
    ]
