# Generated by Django 3.2 on 2021-10-09 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_student_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='age',
            field=models.SmallIntegerField(null=True, verbose_name='年龄'),
        ),
    ]
