# Generated by Django 3.2 on 2021-10-09 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_auto_20211009_0708'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='classmate',
            field=models.CharField(default='python脱产12期', max_length=32, verbose_name='班级'),
        ),
    ]
