# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-05-06 01:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='it',
            old_name='it_end_tile',
            new_name='it_end_time',
        ),
        migrations.RenameField(
            model_name='it',
            old_name='it_start_tile',
            new_name='it_start_time',
        ),
    ]
