# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-01-13 00:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20200113_0025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsfavorrecord',
            name='news',
        ),
        migrations.RemoveField(
            model_name='newsfavorrecord',
            name='user',
        ),
        migrations.RemoveField(
            model_name='viewerrecord',
            name='news',
        ),
        migrations.RemoveField(
            model_name='viewerrecord',
            name='user',
        ),
        migrations.AddField(
            model_name='news',
            name='favor',
            field=models.ManyToManyField(related_name='news_favor', to='api.UserInfo', verbose_name='点赞记录'),
        ),
        migrations.AddField(
            model_name='news',
            name='viewer',
            field=models.ManyToManyField(related_name='news_viewer', to='api.UserInfo', verbose_name='浏览器记录'),
        ),
        migrations.AlterField(
            model_name='news',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news', to='api.UserInfo', verbose_name='发布者'),
        ),
        migrations.DeleteModel(
            name='NewsFavorRecord',
        ),
        migrations.DeleteModel(
            name='ViewerRecord',
        ),
    ]
