# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-01-13 02:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20200113_0201'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CommentFavor',
            new_name='CommentFavorRecord',
        ),
    ]
