# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-01-16 11:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_userinfo_follow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, '未开拍'), (2, '预展中'), (3, '拍卖中'), (4, '已结束')], default=1, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='follow',
            field=models.ManyToManyField(blank=True, related_name='_userinfo_follow_+', to='api.UserInfo', verbose_name='关注'),
        ),
    ]
