# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-01-17 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_auto_20200117_0825'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='blance',
            new_name='balance',
        ),
        migrations.AlterField(
            model_name='auctionitem',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, '待成交'), (2, '成交'), (3, '流拍')], default=1, verbose_name='状态'),
        ),
    ]
