# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-02-12 12:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0053_order_twenty_four_task_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepositDeduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(verbose_name='金额')),
            ],
        ),
        migrations.AlterField(
            model_name='auctionitem',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, '未开拍'), (2, '预展中'), (3, '拍卖中'), (4, '成交'), (5, '流拍'), (6, '逾期未支付')], default=1, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, '未支付'), (2, '待收货'), (3, '已完成'), (4, '逾期未支付')], verbose_name='状态'),
        ),
        migrations.AddField(
            model_name='depositdeduct',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Order', verbose_name='订单'),
        ),
    ]
