# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-02-14 06:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0057_auto_20200214_1429'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='apply_end_task_id',
            new_name='apply_stop_task_id',
        ),
    ]
