# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-23 07:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_userinfo_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='classes',
            field=models.IntegerField(choices=[(11, '全栈1期'), (21, '全栈3期')], default=1, verbose_name='班级'),
        ),
    ]
