# Generated by Django 2.2 on 2022-02-21 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0002_auto_20220221_0908'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'verbose_name': '11-用户表', 'verbose_name_plural': '11-用户表'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': '10-评价表', 'verbose_name_plural': '10-评价表'},
        ),
        migrations.AlterModelOptions(
            name='coursechapter',
            options={'verbose_name': '06-课程章节表', 'verbose_name_plural': '06-课程章节表'},
        ),
        migrations.AlterModelOptions(
            name='courseoutline',
            options={'verbose_name': '12-课程大纲表', 'verbose_name_plural': '12-课程大纲表'},
        ),
        migrations.AlterModelOptions(
            name='coursesection',
            options={'verbose_name': '07-课程课时表', 'verbose_name_plural': '07-课程课时表'},
        ),
        migrations.AlterModelOptions(
            name='degreecourse',
            options={'verbose_name': '05-学位课程表', 'verbose_name_plural': '05-学位课程表'},
        ),
        migrations.AlterModelOptions(
            name='oftenaskedquestion',
            options={'verbose_name': '09-常见问题表', 'verbose_name_plural': '09-常见问题表'},
        ),
        migrations.AlterModelOptions(
            name='pricepolicy',
            options={'verbose_name': '08-价格策略表', 'verbose_name_plural': '08-价格策略表'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': '04-教师表', 'verbose_name_plural': '04-教师表'},
        ),
    ]
