# Generated by Django 2.0 on 2019-01-28 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='orderdetail',
            unique_together=set(),
        ),
    ]
