# Generated by Django 2.0 on 2019-02-01 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0002_auto_20190128_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='money_equivalent_value',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='等值货币'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='off_percent',
            field=models.PositiveSmallIntegerField(blank=True, default=100, help_text='只针对折扣券，例7.9折，写79', null=True, verbose_name='折扣百分比'),
        ),
    ]
