# Generated by Django 2.2 on 2020-01-13 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleimage',
            name='link',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='文件图片'),
        ),
    ]
