# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-01-11 00:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200110_0935'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsimage',
            old_name='img',
            new_name='path',
        ),
    ]
