# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-01-13 02:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20200113_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentrecord',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='评论时间'),
        ),
    ]
