# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-02-06 01:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_auto_20200205_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='cover',
            field=models.FileField(max_length=128, upload_to='', verbose_name='封面'),
        ),
    ]
