# Generated by Django 2.0 on 2018-10-09 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='作者的姓名')),
            ],
            options={
                'verbose_name_plural': '03-作者表',
                'db_table': '03-作者表',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='图书名称')),
                ('chapter', models.IntegerField(choices=[(1, 'Python'), (2, 'Go'), (3, 'Linux')], verbose_name='图书的类别')),
                ('pub_time', models.DateField(verbose_name='图书的出版日期')),
                ('Author', models.ManyToManyField(to='SerDemo.Author')),
            ],
            options={
                'verbose_name_plural': '01-图书表',
                'db_table': '01-图书表',
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='出版社的名称')),
            ],
            options={
                'verbose_name_plural': '02-出版社表',
                'db_table': '02-出版社表',
            },
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(on_delete=None, to='SerDemo.Publisher'),
        ),
    ]
