# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-01-15 07:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200115_0937'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentrecord',
            name='root',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roots', to='api.CommentRecord', verbose_name='根评论'),
        ),
        migrations.AlterField(
            model_name='commentrecord',
            name='reply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replys', to='api.CommentRecord', verbose_name='回复'),
        ),
    ]
