# Generated by Django 3.2 on 2022-04-01 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_rename_good_award_goods'),
    ]

    operations = [
        migrations.RenameField(
            model_name='award',
            old_name='goods',
            new_name='good',
        ),
    ]
