# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-29 03:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeployServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, '发布中'), (2, '失败'), (3, '成功')], verbose_name='状态')),
            ],
        ),
        migrations.CreateModel(
            name='DeployTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(help_text='任务ID格式为：项目-版本-时间，例如 cmdb-v1-201911012359.zip', max_length=64, verbose_name='任务ID')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, '待发布'), (2, '发布中'), (3, '成功'), (4, '失败')], default=1, verbose_name='状态')),
                ('tag', models.CharField(blank=True, max_length=32, null=True, verbose_name='版本')),
                ('branch', models.CharField(blank=True, max_length=32, null=True, verbose_name='分支')),
                ('commit', models.CharField(blank=True, max_length=40, null=True, verbose_name='提交记录')),
                ('env', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.ProjectEnv', verbose_name='环境')),
            ],
        ),
        migrations.AddField(
            model_name='deployserver',
            name='deploy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.DeployTask', verbose_name='部署'),
        ),
        migrations.AddField(
            model_name='deployserver',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Server', verbose_name='服务器'),
        ),
    ]
