# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-30 03:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20191129_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='deploytask',
            name='deploy_servers',
            field=models.ManyToManyField(blank=True, to='web.Server', verbose_name='真正发布的服务器'),
        ),
        migrations.AddField(
            model_name='deploytask',
            name='deploy_type',
            field=models.PositiveSmallIntegerField(choices=[(1, '全量服务器发布'), (2, '自定义服务器发布')], default=1, verbose_name='发布类型'),
        ),
    ]
