# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-30 06:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20191130_1151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deploytask',
            name='deploy_servers',
        ),
    ]
