# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-30 06:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_remove_deploytask_deploy_servers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deployserver',
            name='deploy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.DeployTask', verbose_name='发布任务'),
        ),
        migrations.AlterField(
            model_name='deployserver',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, '待发布'), (2, '发布中'), (3, '失败'), (4, '成功')], verbose_name='状态'),
        ),
    ]
