# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-04 14:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20191130_1434'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=32, verbose_name='文本')),
                ('status', models.CharField(choices=[('gray', '待执行'), ('green', '成功'), ('red', '失败')], max_length=32, verbose_name='状态')),
            ],
        ),
        migrations.AddField(
            model_name='deploytask',
            name='xx',
            field=models.ManyToManyField(through='web.DeployServer', to='web.Server', verbose_name='自定义服务器'),
        ),
        migrations.AlterField(
            model_name='deployserver',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, '待发布'), (2, '发布中'), (3, '失败'), (4, '成功')], default=1, verbose_name='状态'),
        ),
        migrations.AddField(
            model_name='diagram',
            name='deploy_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.DeployServer', verbose_name='服务器发布记录'),
        ),
        migrations.AddField(
            model_name='diagram',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.Diagram', verbose_name='父节点'),
        ),
        migrations.AddField(
            model_name='diagram',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.DeployTask', verbose_name='发布任务'),
        ),
    ]
