# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-12-06 04:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_auto_20191204_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagram',
            name='log',
            field=models.TextField(blank=True, null=True, verbose_name='日志'),
        ),
    ]
