# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-12-06 04:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_diagram_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagram',
            name='is_diagram',
            field=models.IntegerField(choices=[(0, '日志'), (1, '图表')], default=1, verbose_name='是否图表'),
        ),
    ]
