# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-12-06 08:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_auto_20191206_0801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectenv',
            name='env',
            field=models.CharField(choices=[('test', '测试'), ('prod', '正式')], max_length=32, verbose_name='环境'),
        ),
    ]
