# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-12-09 04:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_auto_20191209_0416'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hookscript',
            name='env',
        ),
    ]
