# Generated by Django 3.2 on 2021-12-29 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_deartment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Deartment',
            new_name='Department',
        ),
    ]
