# Generated by Django 3.2 on 2021-12-30 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_curse'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Curse',
            new_name='Course',
        ),
    ]
