# Generated by Django 3.2 on 2022-01-04 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_studyrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='courserecord',
            name='course_memo',
            field=models.TextField(blank=True, null=True, verbose_name='内容概要'),
        ),
        migrations.AddField(
            model_name='courserecord',
            name='course_title',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='本节课程名称'),
        ),
        migrations.AddField(
            model_name='courserecord',
            name='homework',
            field=models.TextField(blank=True, null=True, verbose_name='作业内容'),
        ),
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(max_length=64, null=True, verbose_name='密码'),
        ),
        migrations.AddField(
            model_name='studyrecord',
            name='homework_comment',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='导师点评'),
        ),
        migrations.AddField(
            model_name='studyrecord',
            name='homework_score',
            field=models.PositiveIntegerField(default=0, verbose_name='作业成绩'),
        ),
        migrations.AddField(
            model_name='studyrecord',
            name='homework_url',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='作业'),
        ),
    ]
