# Generated by Django 3.2 on 2022-03-29 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='media_id',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='微信媒体ID'),
        ),
    ]
