# Generated by Django 3.2 on 2022-03-29 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('msg', '0003_auto_20220329_1723'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
