# Generated by Django 3.2 on 2022-03-31 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msg', '0005_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='发送内容'),
        ),
        migrations.AlterField(
            model_name='message',
            name='interaction',
            field=models.IntegerField(choices=[(1, '48小时互动'), (2, '不限')], default=1, verbose_name='48小时互动'),
        ),
    ]
