# Generated by Django 3.2.4 on 2021-06-20 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.SmallIntegerField(choices=[(1, '管理员'), (2, '超级管理员')], default=1, verbose_name='用户类型')),
                ('username', models.CharField(db_index=True, max_length=32, verbose_name='用户名')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
                ('mobile', models.CharField(blank=True, db_index=True, max_length=11, null=True, verbose_name='手机号')),
                ('active', models.BooleanField(default=True, help_text='False表示删除', verbose_name='是否激活')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=32, verbose_name='用户名')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='账户余额')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('active', models.BooleanField(default=True, help_text='False表示删除', verbose_name='是否激活')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.administrator', verbose_name='创建者')),
            ],
        ),
        migrations.CreateModel(
            name='PricePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(verbose_name='数量')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='价格')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField(choices=[(1, '待执行'), (2, '正在执行'), (3, '已完成'), (4, '失败')], default=1, verbose_name='状态')),
                ('oid', models.CharField(help_text='用户ID+时间戳', max_length=64, verbose_name='订单号')),
                ('url', models.URLField(verbose_name='视频地址')),
                ('count', models.IntegerField(verbose_name='数量')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='价格')),
                ('old_view_count', models.IntegerField(default=0, verbose_name='原播放量')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.customer', verbose_name='客户')),
            ],
        ),
        migrations.CreateModel(
            name='ChargeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='充值金额')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='充值时间')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.administrator', verbose_name='管理员')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.customer', verbose_name='客户')),
            ],
        ),
    ]
