# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-03 08:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0002_permission_is_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='icon',
            field=models.CharField(blank=True, help_text='菜单才设置图标', max_length=32, null=True, verbose_name='图标'),
        ),
    ]
