# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-03 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0004_auto_20180803_0921'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='icon',
            field=models.CharField(default=1, max_length=32, verbose_name='图标'),
            preserve_default=False,
        ),
    ]
