# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-04 07:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0009_auto_20180804_0714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permission',
            name='code',
        ),
        migrations.AlterField(
            model_name='permission',
            name='url',
            field=models.CharField(max_length=128, unique=True, verbose_name='含正则的URL'),
        ),
    ]
