# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-04 10:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0011_permission_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='permission',
            old_name='code',
            new_name='name',
        ),
    ]
