# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-04 10:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0012_auto_20180804_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='name',
            field=models.CharField(max_length=64, unique=True, verbose_name='代码'),
        ),
    ]
