# Generated by Django 3.2 on 2022-03-28 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_publicnumbers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicnumbers',
            name='authorizer_access_token',
            field=models.CharField(max_length=255, verbose_name='授权token'),
        ),
    ]
