# Generated by Django 2.2 on 2020-02-16 03:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orders', models.IntegerField(blank=True, default=0, null=True, verbose_name='排序')),
                ('is_show', models.BooleanField(default=True, verbose_name='是否展示')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('types', models.IntegerField(choices=[('赞赏', 0), ('购买', 1), ('提现', 2), ('充值', 3), ('其他', 4)], default=4, verbose_name='类型')),
                ('money', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='金额')),
                ('status', models.IntegerField(choices=[('未支付', 0), ('已支付', 1)], default=0, verbose_name='状态')),
                ('goods', models.CharField(max_length=150, verbose_name='物品名称')),
                ('goods_type', models.IntegerField(choices=[('其他', 0), ('文章', 1)], default=0, verbose_name='物品类型')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='record_list', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户收支记录',
                'verbose_name_plural': '用户收支记录',
                'db_table': 'rr_user_record',
            },
        ),
    ]
