# Generated by Django 2.2 on 2020-02-16 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='other_user',
            field=models.IntegerField(default=0, verbose_name='用户'),
        ),
    ]
