# Generated by Django 2.2 on 2020-02-16 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_record_other_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='goods_id',
            field=models.IntegerField(default=0, verbose_name='物品名称'),
        ),
    ]
