# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-01-11 01:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20200111_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Topic', verbose_name='话题'),
        ),
    ]
