# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-01-11 09:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20200111_0241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsimage',
            name='path',
        ),
        migrations.AddField(
            model_name='newsimage',
            name='cos_path',
            field=models.CharField(default=1, max_length=128, verbose_name='腾讯对象存储中图片路径'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='newsimage',
            name='key',
            field=models.CharField(help_text='用于以后在腾讯对象存储中删除', max_length=128, verbose_name='腾讯对象存储中的文件名'),
        ),
    ]
