# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-01-13 00:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_commentrecord_favor_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default='2011-11-11', verbose_name='创建时间'),
            preserve_default=False,
        ),
    ]
