# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-01-13 00:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_news_create_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ViewRecord',
            new_name='ViewerRecord',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='view_count',
            new_name='viewer_count',
        ),
    ]
