# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-01-16 11:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_auto_20200116_1103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='img',
        ),
        migrations.AddField(
            model_name='auction',
            name='cover',
            field=models.CharField(default=1, max_length=64, verbose_name='封面'),
            preserve_default=False,
        ),
    ]
