# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-01-17 01:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_auto_20200116_1149'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='收货人姓名')),
                ('phone', models.CharField(max_length=11, verbose_name='联系电话')),
                ('city', models.CharField(max_length=64, verbose_name='收货地址')),
                ('detail', models.CharField(max_length=64, verbose_name='详细地址')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.UserInfo', verbose_name='用户')),
            ],
        ),
        migrations.CreateModel(
            name='DepositRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, '未支付'), (2, '支付成功')], verbose_name='状态')),
                ('uid', models.CharField(max_length=64, verbose_name='流水号')),
                ('deposit_type', models.SmallIntegerField(choices=[(1, '单品保证金'), (2, '全场保证金')], verbose_name='保证金类型')),
                ('py_type', models.SmallIntegerField(choices=[(1, '微信'), (2, '余额'), (3, '其他')], verbose_name='支付方式')),
                ('amount', models.PositiveIntegerField(verbose_name='金额')),
            ],
        ),
        migrations.CreateModel(
            name='DepositRefundRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=64, verbose_name='流水号')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, '退款中'), (2, '退款成功')], verbose_name='状态')),
                ('amount', models.PositiveIntegerField(verbose_name='退款金额')),
                ('deposit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.DepositRecord', verbose_name='保证金')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, '未支付'), (2, '待收货'), (2, '已完成'), (3, '逾期未支付')], verbose_name='状态')),
                ('uid', models.CharField(max_length=64, verbose_name='流水号')),
                ('price', models.PositiveIntegerField(verbose_name='出价')),
                ('real_price', models.PositiveIntegerField(null=True, verbose_name='实际支付金额')),
                ('deposit_price', models.PositiveIntegerField(verbose_name='使用保证金金额')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Address', verbose_name='收货地址')),
                ('deposit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.DepositRecord', verbose_name='保证金')),
            ],
        ),
        migrations.RemoveField(
            model_name='auctionitem',
            name='img',
        ),
        migrations.AddField(
            model_name='auction',
            name='deposit',
            field=models.PositiveIntegerField(default=1000, verbose_name='全场保证金'),
        ),
        migrations.AddField(
            model_name='auctionitem',
            name='cover',
            field=models.CharField(default=1, max_length=64, verbose_name='拍品封面'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='auctionitem',
            name='deposit',
            field=models.PositiveIntegerField(default=100, verbose_name='单品保证金'),
        ),
        migrations.AlterField(
            model_name='bidrecord',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, '竞价'), (2, '成交'), (3, '逾期未付款')], default=1, verbose_name='状态'),
        ),
        migrations.AddField(
            model_name='order',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.AuctionItem', verbose_name='拍品'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.UserInfo', verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='depositrecord',
            name='auction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Auction', verbose_name='拍卖'),
        ),
        migrations.AddField(
            model_name='depositrecord',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.AuctionItem', verbose_name='拍品'),
        ),
        migrations.AddField(
            model_name='depositrecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.UserInfo', verbose_name='用户'),
        ),
    ]
