# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-01-17 02:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_auto_20200117_0158'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AuctionItemDetail',
            new_name='AuctionItemImage',
        ),
        migrations.AlterModelOptions(
            name='auction',
            options={'verbose_name_plural': '拍卖系列'},
        ),
        migrations.AlterModelOptions(
            name='auctionitem',
            options={'verbose_name_plural': '拍品'},
        ),
        migrations.AlterModelOptions(
            name='auctionitemimage',
            options={'verbose_name_plural': '拍品详细'},
        ),
    ]
