# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-01-17 02:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_auto_20200117_0203'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auctionitemdetail',
            options={'verbose_name_plural': '拍品规格'},
        ),
        migrations.AlterModelOptions(
            name='auctionitemimage',
            options={'verbose_name_plural': '拍品详细图'},
        ),
        migrations.AlterField(
            model_name='auction',
            name='cover',
            field=models.FilePathField(max_length=64, verbose_name='封面'),
        ),
    ]
