# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-01-17 02:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_auto_20200117_0221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionitem',
            name='cover',
            field=models.CharField(max_length=128, verbose_name='拍品封面'),
        ),
    ]
