# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-01-17 08:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_auto_20200117_0223'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionitem',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='成交价'),
        ),
    ]
