# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-02-05 09:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_auto_20200120_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='cover',
            field=models.FileField(max_length=128, upload_to='', verbose_name='封面'),
        ),
        migrations.AlterField(
            model_name='auctionitem',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, '未开拍'), (2, '预展中'), (3, '拍卖中'), (4, '成交'), (5, '流拍')], default=1, verbose_name='状态'),
        ),
    ]
