# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-02-10 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_auto_20200206_0633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionitemimage',
            name='img',
            field=models.FileField(max_length=64, upload_to='', verbose_name='详细图'),
        ),
    ]
