# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-02-11 10:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_auto_20200210_1505'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preview_status', models.SmallIntegerField(choices=[(1, '待执行'), (2, '成功'), (3, '失败')], default=1, verbose_name='预展任务状态')),
                ('preview_task', models.CharField(max_length=64, verbose_name='Celery预展任务ID')),
                ('auction_status', models.SmallIntegerField(choices=[(1, '待执行'), (2, '成功'), (3, '失败')], default=1, verbose_name='拍卖任务状态')),
                ('auction_task', models.CharField(max_length=64, verbose_name='Celery拍卖任务ID')),
                ('auction_end_status', models.SmallIntegerField(choices=[(1, '待执行'), (2, '成功'), (3, '失败')], default=1, verbose_name='拍卖结束任务状态')),
                ('auction_end_task', models.CharField(max_length=64, verbose_name='Celery拍卖结束任务ID')),
                ('auction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.Auction', verbose_name='专场')),
            ],
        ),
    ]
